# Generated by Django 3.1.7 on 2021-07-19 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 14, 57, 45, 453146, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
