# Generated by Django 3.2.4 on 2021-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutableCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.TextField()),
                ('field1', models.JSONField(blank=True, null=True)),
                ('field2', models.JSONField(blank=True, null=True)),
                ('field3', models.JSONField(blank=True, null=True)),
                ('field4', models.JSONField(blank=True, null=True)),
                ('field5', models.JSONField(blank=True, null=True)),
                ('field6', models.JSONField(blank=True, null=True)),
                ('field7', models.JSONField(blank=True, null=True)),
                ('field8', models.JSONField(blank=True, null=True)),
                ('field9', models.JSONField(blank=True, null=True)),
                ('field10', models.JSONField(blank=True, null=True)),
                ('field11', models.JSONField(blank=True, null=True)),
                ('field12', models.JSONField(blank=True, null=True)),
                ('field13', models.JSONField(blank=True, null=True)),
                ('field14', models.JSONField(blank=True, null=True)),
                ('field15', models.JSONField(blank=True, null=True)),
                ('field16', models.JSONField(blank=True, null=True)),
                ('field17', models.JSONField(blank=True, null=True)),
                ('field18', models.JSONField(blank=True, null=True)),
                ('field19', models.JSONField(blank=True, null=True)),
                ('field20', models.JSONField(blank=True, null=True)),
                ('field21', models.JSONField(blank=True, null=True)),
                ('field22', models.JSONField(blank=True, null=True)),
                ('field23', models.JSONField(blank=True, null=True)),
                ('field24', models.JSONField(blank=True, null=True)),
                ('is_shown', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MutableCategory',
                'verbose_name_plural': 'MutableCategories',
            },
        ),
    ]
