# Generated by Django 3.1.7 on 2021-07-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0002_auto_20210702_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
