# Generated by Django 3.2.4 on 2021-07-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0002_mutablecategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutableCategoriesAdmin',
            fields=[
                ('mutablecategories_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CHP.mutablecategories')),
            ],
            bases=('CHP.mutablecategories',),
        ),
    ]
