# Generated by Django 3.1.7 on 2021-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0004_auto_20210722_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='isShown',
            field=models.BooleanField(default=False),
        ),
    ]
