# Generated by Django 3.2.4 on 2021-07-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0004_delete_mutablecategoriesadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MutableCategories',
        ),
    ]
