# Generated by Django 3.2.4 on 2021-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0005_alldata_isshown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='verified',
        ),
        migrations.AlterField(
            model_name='categories',
            name='field1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field21',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field23',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field24',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='field9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
