# Generated by Django 3.2.4 on 2021-07-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('CHP', '0007_user_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usergroup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auth.group'),
        ),
    ]
