# Generated by Django 3.2.4 on 2021-07-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('CHP', '0009_auto_20210728_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usergroup',
        ),
        migrations.AddField(
            model_name='user',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='auth.group'),
        ),
    ]
