# Generated by Django 3.2.4 on 2021-09-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0011_alter_categories_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alldata',
            old_name='field21',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='alldata',
            old_name='field22',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='alldata',
            old_name='field23',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='alldata',
            old_name='field24',
            new_name='phone1',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='field21',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='field22',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='field23',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='field24',
        ),
        migrations.AddField(
            model_name='alldata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='mapUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='phone2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='phone3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
