# Generated by Django 3.2.4 on 2021-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHP', '0013_alter_user_usergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldata',
            name='data',
        ),
        migrations.AddField(
            model_name='alldata',
            name='field1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field21',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field22',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field23',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field24',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='field9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
