"""
Django settings for ICHG project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7unr@u9bz&+4*(pp02^zfd-+94g_x(vb)&n69z)-gv&fn*mlnz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = "CHP.User"
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 587

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CHP',
    'cloudinary'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ICHG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ICHG.wsgi.application'

cloudinary.config( 
  cloud_name = "", 
  api_key = "", 
  api_secret = "" 
)

STATE_LIST =(
                ("AN","Andaman and Nicobar Islands"),
                ("AP","Andhra Pradesh"),
                ("AR","Arunachal Pradesh"),
                ("AS","Assam"),
                ("BR","Bihar"),
                ("CG","Chhattisgarh"),
                ("CH","Chandigarh"),
                ("DN","Dadra and Nagar Haveli"),
                ("DD","Daman and Diu"),
                ("DL","Delhi"),
                ("GA","Goa"),
                ("GJ","Gujarat"),
                ("HR","Haryana"),
                ("HP","Himachal Pradesh"),
                ("JK","Jammu and Kashmir"),
                ("JH","Jharkhand"),
                ("KA","Karnataka"),
                ("KL","Kerala"),
                ("LA","Ladakh"),
                ("LD","Lakshadweep"),
                ("MP","Madhya Pradesh"),
                ("MH","Maharashtra"),
                ("MN","Manipur"),
                ("ML","Meghalaya"),
                ("MZ","Mizoram"),
                ("NL","Nagaland"),
                ("OD","Odisha"),
                ("PB","Punjab"),
                ("PY","Pondicherry"),
                ("RJ","Rajasthan"),
                ("SK","Sikkim"),
                ("TN","Tamil Nadu"),
                ("TS","Telangana"),
                ("TR","Tripura"),
                ("UP","Uttar Pradesh"),
                ("UK","Uttarakhand"),
                ("WB","West Bengal")
            )

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ichg',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'sql_mode': 'traditional',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
